### PR TITLE
[saas]: (feat): Billing with stripe

### PR DESCRIPTION
**Pull request by DaniEnsi**
Hey,
I dont know if you were already working on this, or if you even want others to work on it, but i have recently been doing a lot of stripe stuff and loved your idea of making an extremely cool opensource boilerplate. I tried to adapt the way you did the other stuff as far as I could, but some things might need a look over in terms of security...

You now also need to forward the webhook using stripe cli when in dev...
`stripe listen --forward-to localhost:3000/api/users/webhooks/stripe`

### CODE REVIEW

**Comment by alifarooq9** [comment]
Hey @DaniEnsi,

Thanks for opening a PR. I was in fact not working on the billing stuff. I realized something I should give a detailed roadmap and mention what am I currently working on, I'm currently working on Docs, Blog and change log stuff.

On the first look of the PR, it looks good. I will be taking a deep look after completing Docs stuff, then will tell you if I have any improvements or suggestions.

Thanks

**Comment by DaniEnsi** [comment]
@alifarooq9 
I checked everything now and deployed it myself to check if it works, it would help if you could allow checks for your repo, so i can fix any errors here, if there are still any...

Thanks and well done on making such a cool framework alr :)

**Comment by alifarooq9** [comment]
> @alifarooq9 I checked everything now and deployed it myself to check if it works, it would help if you could allow checks for your repo, so i can fix any errors here, if there are still any...
> 
> Thanks and well done on making such a cool framework alr :)

Okay, I will try add checks as soon as possible.
I have never added checks before if you have any suggestions, it would be very appreciated.

**Comment by DaniEnsi** [comment]
> > @alifarooq9 I checked everything now and deployed it myself to check if it works, it would help if you could allow checks for your repo, so i can fix any errors here, if there are still any...
> > Thanks and well done on making such a cool framework alr :)
> 
> Okay, I will try add checks as soon as possible. I have never added checks before if you have any suggestions, it would be very appreciated.

For most parts it would just be the vercel checks to see if the pull requests build. This allows any committer to see whats preventing their PR to compile...

**Vercel Docs:**
[Preview URLs for the Latest Changes for Each Pull Request](https://vercel.com/docs/deployments/git/vercel-for-github#preview-urls-for-the-latest-changes-for-each-pull-request)
The latest push to any pull request will automatically be made available at a unique [preview URL](https://vercel.com/docs/deployments/preview-deployments#preview-urls) based on the project name, branch, and team or username. These URLs will be provided through a comment on each pull request. Vercel also supports Comments on preview deployments made from PRs on GitHub. [Learn more about Comments on preview deployments in GitHub here](https://vercel.com/docs/deployments/preview-deployments#github-integration).

**Comment by DaniEnsi** [comment]
image

**Comment by alifarooq9** [comment]
> image

I have authorized it

**Comment by DaniEnsi** [comment]
Hey, I still cant seem to be able to view weather my pr is working... It still says that "authentication is required" on any commit i pushed....

image

image

**Comment by alifarooq9** [comment]
> Hey, I still cant seem to be able to view weather my pr is working... It still says that "authentication is required" on any commit i pushed....
> 
> image image

I approved this one. Do you know how I can set auto approve? or should I add github actions for linting?

**Comment by DaniEnsi** [comment]
> > Hey, I still cant seem to be able to view weather my pr is working... It still says that "authentication is required" on any commit i pushed....
> > image image
> 
> I approved this one. Do you know how I can set auto approve? Try deploying by your self then create a PR because If I disable approve feature, anyone can trigger a build by creating PR. If will soon add github actions for linting, it will also help to check error.

Yh, no thats all done, I did deploy it on my own vercel and it worked, so thats why I am wondering why this one is failing... Could you maybe tell me the error it throwing as i cant see ... :)

**Comment by DaniEnsi** [comment]
image

**Comment by alifarooq9** [comment]
@DaniEnsi 

My vision was to add organizational level billing, and recent lemon squeezy is becoming popular. I was thinking that lemon squeezy will be better option. What are you thoughts one this?

**Comment by DaniEnsi** [comment]
@alifarooq9 

The Organisation based paying is a great solution indeed I thought about too. I have so say that I have used stripe in the past and was always happy with their docs and api, so I went for stripe, I had a look at lemonsqueezy and I have to say that it looks promising however for a boilerplate I thought that sticking to a well accepted and known platform like stripe would be the better choice. Looking back idk why I didn't connect the payment to orgs and rather to users. I will fix that. Lastly I also just wanted to add that payments for a boilerplate is such a hard section to master that I thought it might just help you at least if you had like a base to start from... I thought of adding fully custom checkout and billing to instead of redirecting to the stripe checkout pages but I would've just been so much more complicated to do and work with for anyone late rising the boilerplate...

Feel free to correct me if you disagree on some points :)

**Comment by alifarooq9** [comment]
@DaniEnsi 

I am getting this error on vercel preview deployment

Screenshot 2024-04-04 at 2 58 19 PM

**Comment by DaniEnsi** [comment]
@alifarooq9 
I fixed the vercel error, it was due to me using yarn instead of pnpm

**Comment by DaniEnsi** [comment]
@alifarooq9
It should work now, if you want to try again...

**Comment by alifarooq9** [comment]
Hey @DaniEnsi,

I have researched about stripe and lemonsqueezy both, after researching I have come up with a conclusion of using lemonsqueezy for now, in future I will add stripe as an option but for now lemonsqueezy will be the payment solution.

Thank you for your pull request, I have one suggestion if you decided to contribute in the future. I would suggest please do well structured commits: [Committing conventions](https://www.conventionalcommits.org/en/v1.0.0/)

I will be closing this PR Soon,
Thank you

**Comment by DaniEnsi** [comment]
Sure no problem... I get that you are doing your best to make it perfect, and stripe might not be the best for that. If I have any future ideas, etc. I will certainly do another pr...

Best of Luck with the rest :)

**Comment by DaniEnsi** [comment]
@alifarooq9 
quick question besides the pr, what program did u use to make your banner on the readme? Was it just photoshop or is there anything else?

thanks

**Comment by alifarooq9** [comment]
> @alifarooq9 
> quick question besides the pr, what program did u use to make your banner on the readme? Was it just photoshop or is there anything else?
> 
> thanks

Used figma for this

**Comment by lilac** [comment]
>I have researched about stripe and lemonsqueezy both, after researching I have come up with a conclusion of using lemonsqueezy for now, in future I will add stripe as an option but for now lemonsqueezy will be the payment solution.

Could you explain more on the conclusion. i think stripe has a much larger user base. In fact I haven't heard of lemonsqueezy before. In addition, the pricing of lemonsqueecy (5%) is more expensive than that of Stripe. I can't think of any reasons to use it.

**Pull request closed without merging**
